language: node_js
node_js:
   - "0.8"
   - "0.10"
# http://gearchicken.com/wordpress/?p=105
before_install:
# We need this line to have g++4.8 available in apt
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - npm update
  # Put local npm modules .bin on PATH
  - export PATH=./node_modules/.bin/:$PATH
  # Install node-gyp and node-pre-gyp so it is available for packaging and publishing
  - npm install node-gyp -g
  - npm install plz -g
  - npm run-script clean
before_script:
  - coffee -c -o lib src
install:
  - sudo apt-get install -qq gcc-4.8 g++-4.8
  # We want to compile with g++ 4.8 when rather than the default g++
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
  # Add xz utils and development package
  - sudo apt-get install -qq xz-utils liblzma-dev
  # Ensure source install works and compiles correctly
  - npm run-script build
  # test our module
  - npm test
after_success:
